# Starter pipeline
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'sonar-integracion'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Sonar-integracion_Demo'
    cliProjectName: 'Demo'
    cliSources: '.'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
- task: SonarCloudAnalyze@1

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'